app = "savelal"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8501"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"
