[phases.setup]
nixPkgs = ["python3", "python39", "gcc", "postgresql"]
aptPkgs = ["libpq-dev", "build-essential"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["chmod +x build.sh", "./build.sh"]

[phases.start]
cmds = [". /opt/venv/bin/activate && streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"]

[start]
cmd = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
