[phases.setup]
nixPkgs = ["python3", "python39", "gcc", "postgresql"]
aptPkgs = ["libpq-dev", "build-essential"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "chmod +x build.sh",
  "chmod +x entrypoint.sh",
  "./build.sh"
]

[phases.start]
cmds = ["./entrypoint.sh"]

[start]
cmd = "./entrypoint.sh"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
STREAMLIT_SERVER_ENABLE_STATIC_SERVING = "true"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_ENABLE_CORS = "true"
SKIP_DB_CHECK = "true"
