[server]
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false
headless = true
enableStaticServing = true
port = 8080
address = "0.0.0.0"
baseUrlPath = ""
allowWebsocketOrigin = "*"
enableWebsocketConnectionReuse = true

[browser]
gatherUsageStats = false
serverAddress = "gobeklitepe-5hzle.kinsta.app"
serverPort = 443

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#212121"
font = "sans serif"

[runner]
magicEnabled = true
fastReruns = true

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
